config/routes.rb
Rails.application.routes.draw do
  # トップ
  get "/" => "home#top"
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  # ログイン
  get "login" => "users#login_form"
  post "login" => "users#login"

  get "mypage" => "users#show"

  # イラスト投稿
  get "upload" => "illusts#upload_form"
  post "upload" => "illusts#upload"
  get "illust/edit/:id" => "illusts#edit"
  post "illust/update/:id" => "illusts#update"

  # ユーザ
  # 新規登録
  get "signup" => "users#new"
  post "users/create" => "users#create"
  get "users/:id" => "users#show"

  # 画像アップロード
  get "images" => "images#index"

  # 質問ページ
  get "questions/:id" => "questions#index"
  post "questions/upload/:id" => "questions#upload"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>晒せ！</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application' %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css">
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  </head>

  <body>
    <div id="app">
      <header>
        <nav>
          <div class="header-logo">
            <%= link_to("晒せ！", "/") %>
          </div>

          <ul class="header-menus">
            <% if user_signed_in? %>
              <li><%= link_to 'マイページ', mypage_path %></li>
              <li><%= link_to 'イラスト投稿', upload_path, data: {"turbolinks" => false } %></li>
              <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'アカウント登録', new_user_registration_path %></li>
              <li><%= link_to 'ログイン', new_user_session_path %></li>
            <% end %>

          </ul>
        </nav>
      </header>
      <% if flash[:notice] %>
        <p class="notice"><%= notice %></p>
      <% else %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>